version: "3.9"
services:
  haproxy:
    image: haproxy:2.5.4-alpine
    ports:
      - "8080:80"
    environment:
      TZ: "asia/seoul"
    volumes:
      - "./conf/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    depends_on:
      - nginx
  nginx:
    image: nginx:1.21.6-alpine
    ports:
      - "8081:80"
    environment:
      TZ: "asia/seoul"
    volumes:
      - "./conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/nginx/conf.d:/etc/nginx/conf.d"
    depends_on:
      - apache
  apache:
    image: httpd:2.4.52-alpine
    ports:
      - "8082:80"
    environment:
      TZ: "asia/seoul"
    volumes:
      - "./conf/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf"
    depends_on:
      - web
  web:
    build: .
    ports:
      - "8085:80"
    environment:
      TZ: "asia/seoul"
      PORT: "80"
    volumes: # using local source
      - ".:/home/app"